// Objective-C API for talking to github.com/web3.go/mobile Go package.
//   gobind -lang=objc github.com/web3.go/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Web3go_H__
#define __Web3go_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Web3goAccount;
@class Web3goAccounts;
@class Web3goAddress;
@class Web3goAddresses;
@class Web3goBigInt;
@class Web3goBigInts;
@class Web3goBlock;
@class Web3goBloom;
@class Web3goBoundContract;
@class Web3goCallMsg;
@class Web3goCallOpts;
@class Web3goContext;
@class Web3goCriteria;
@class Web3goEnode;
@class Web3goEnodes;
@class Web3goEthereumClient;
@class Web3goFilterQuery;
@class Web3goGosHash;
@class Web3goHash;
@class Web3goHashes;
@class Web3goHeader;
@class Web3goHeaders;
@class Web3goHomesteadSigner;
@class Web3goInfo;
@class Web3goInterface;
@class Web3goInterfaces;
@class Web3goKeyStore;
@class Web3goLog;
@class Web3goLogs;
@class Web3goMessage;
@class Web3goMessages;
@class Web3goNewMessage;
@class Web3goNode;
@class Web3goNodeConfig;
@class Web3goNodeInfo;
@class Web3goNonce;
@class Web3goPeerInfo;
@class Web3goPeerInfos;
@class Web3goPrivateKey;
@class Web3goPublicKey;
@class Web3goReceipt;
@class Web3goSigner2;
@class Web3goStrings;
@class Web3goSubscription;
@class Web3goSyncProgress;
@class Web3goTopics;
@class Web3goTransactOpts;
@class Web3goTransaction;
@class Web3goTransactions;
@protocol Web3goFilterLogsHandler;
@class Web3goFilterLogsHandler;
@protocol Web3goNewHeadHandler;
@class Web3goNewHeadHandler;
@protocol Web3goSigner;
@class Web3goSigner;

@protocol Web3goFilterLogsHandler <NSObject>
- (void)onError:(NSString*)failure;
- (void)onFilterLogs:(Web3goLog*)log;
@end

@protocol Web3goNewHeadHandler <NSObject>
- (void)onError:(NSString*)failure;
- (void)onNewHead:(Web3goHeader*)header;
@end

@protocol Web3goSigner <NSObject>
- (Web3goTransaction*)sign:(Web3goAddress*)p0 p1:(Web3goTransaction*)p1 error:(NSError**)error;
@end

/**
 * Account represents a stored key.
 */
@interface Web3goAccount : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * GetAddress retrieves the address associated with the account.
 */
- (Web3goAddress*)getAddress;
/**
 * GetURL retrieves the canonical URL of the account.
 */
- (NSString*)getURL;
@end

/**
 * Accounts represents a slice of accounts.
 */
@interface Web3goAccounts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * Get returns the account at the given index from the slice.
 */
- (Web3goAccount*)get:(long)index error:(NSError**)error;
/**
 * Set sets the account at the given index in the slice.
 */
- (BOOL)set:(long)index account:(Web3goAccount*)account error:(NSError**)error;
/**
 * Size returns the number of accounts in the slice.
 */
- (long)size;
@end

/**
 * Address represents the 20 byte address of an Ethereum account.
 */
@interface Web3goAddress : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewAddressFromBytes converts a slice of bytes to a hash value.
 */
- (instancetype)initFromBytes:(NSData*)binary;
/**
 * NewAddressFromHex converts a hex string to a address value.
 */
- (instancetype)initFromHex:(NSString*)hex;
/**
 * GetBytes retrieves the byte representation of the address.
 */
- (NSData*)getBytes;
/**
 * GetHash retrives the Hash representation of the address.
 */
- (Web3goHash*)getHash;
/**
 * GetHex retrieves the hex string representation of the address.
 */
- (NSString*)getHex;
/**
 * SetBytes sets the specified slice of bytes as the address value.
 */
- (BOOL)setBytes:(NSData*)address error:(NSError**)error;
/**
 * SetHex sets the specified hex string as the address value.
 */
- (BOOL)setHex:(NSString*)address error:(NSError**)error;
@end

/**
 * Addresses represents a slice of addresses.
 */
@interface Web3goAddresses : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewAddresses creates a slice of uninitialized addresses.
 */
- (instancetype)init:(long)size;
/**
 * NewAddressesEmpty creates an empty slice of Addresses values.
 */
- (instancetype)initEmpty;
/**
 * Append adds a new address element to the end of the slice.
 */
- (void)append:(Web3goAddress*)address;
/**
 * Get returns the address at the given index from the slice.
 */
- (Web3goAddress*)get:(long)index error:(NSError**)error;
/**
 * Set sets the address at the given index in the slice.
 */
- (BOOL)set:(long)index address:(Web3goAddress*)address error:(NSError**)error;
/**
 * Size returns the number of addresses in the slice.
 */
- (long)size;
@end

/**
 * A BigInt represents a signed multi-precision integer.
 */
@interface Web3goBigInt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewBigInt allocates and returns a new BigInt set to x.
 */
- (instancetype)init:(int64_t)x;
/**
 * GetBytes returns the absolute value of x as a big-endian byte slice.
 */
- (NSData*)getBytes;
/**
 * GetInt64 returns the int64 representation of x. If x cannot be represented in
an int64, the result is undefined.
 */
- (int64_t)getInt64;
/**
 * GetString returns the value of x as a formatted string in some number base.
 */
- (NSString*)getString:(long)base;
/**
 * SetBytes interprets buf as the bytes of a big-endian unsigned integer and sets
the big int to that value.
 */
- (void)setBytes:(NSData*)buf;
/**
 * SetInt64 sets the big int to x.
 */
- (void)setInt64:(int64_t)x;
/**
 * SetString sets the big int to x.

The string prefix determines the actual conversion base. A prefix of "0x" or
"0X" selects base 16; the "0" prefix selects base 8, and a "0b" or "0B" prefix
selects base 2. Otherwise the selected base is 10.
 */
- (void)setString:(NSString*)x base:(long)base;
/**
 * Sign returns:

	-1 if x <  0
	 0 if x == 0
	+1 if x >  0
 */
- (long)sign;
/**
 * String returns the value of x as a formatted decimal string.
 */
- (NSString*)string;
@end

/**
 * BigInts represents a slice of big ints.
 */
@interface Web3goBigInts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewBigInts creates a slice of uninitialized big numbers.
 */
- (instancetype)init:(long)size;
/**
 * Get returns the bigint at the given index from the slice.
 */
- (Web3goBigInt*)get:(long)index error:(NSError**)error;
/**
 * Set sets the big int at the given index in the slice.
 */
- (BOOL)set:(long)index bigint:(Web3goBigInt*)bigint error:(NSError**)error;
/**
 * Size returns the number of big ints in the slice.
 */
- (long)size;
@end

/**
 * Block represents an entire block in the Ethereum blockchain.
 */
@interface Web3goBlock : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewBlockFromJSON parses a block from a JSON data dump.
 */
- (instancetype)initFromJSON:(NSString*)data;
/**
 * NewBlockFromRLP parses a block from an RLP data dump.
 */
- (instancetype)initFromRLP:(NSData*)data;
/**
 * EncodeJSON encodes a block into a JSON data dump.
 */
- (NSString*)encodeJSON:(NSError**)error;
/**
 * EncodeRLP encodes a block into an RLP data dump.
 */
- (NSData*)encodeRLP:(NSError**)error;
/**
 * GetBloom ...
 */
- (Web3goBloom*)getBloom;
/**
 * GetCoinbase ...
 */
- (Web3goAddress*)getCoinbase;
/**
 * GetDifficulty ...
 */
- (Web3goBigInt*)getDifficulty;
/**
 * GetExtra ...
 */
- (NSData*)getExtra;
/**
 * GetGasLimit ...
 */
- (int64_t)getGasLimit;
/**
 * GetGasUsed ...
 */
- (int64_t)getGasUsed;
/**
 * GetHash ...
 */
- (Web3goHash*)getHash;
/**
 * GetHeader ...
 */
- (Web3goHeader*)getHeader;
/**
 * GetMixDigest ...
 */
- (Web3goHash*)getMixDigest;
/**
 * GetNonce ...
 */
- (int64_t)getNonce;
/**
 * GetNumber ...
 */
- (int64_t)getNumber;
/**
 * GetParentHash ...
 */
- (Web3goHash*)getParentHash;
/**
 * GetReceiptHash ...
 */
- (Web3goHash*)getReceiptHash;
/**
 * GetRoot ...
 */
- (Web3goHash*)getRoot;
/**
 * GetTime ...
 */
- (int64_t)getTime;
/**
 * GetTransaction ...
 */
- (Web3goTransaction*)getTransaction:(Web3goHash*)hash;
/**
 * GetTransactions ...
 */
- (Web3goTransactions*)getTransactions;
/**
 * GetTxHash ...
 */
- (Web3goHash*)getTxHash;
/**
 * GetUncleHash ...
 */
- (Web3goHash*)getUncleHash;
/**
 * GetUncles ...
 */
- (Web3goHeaders*)getUncles;
@end

/**
 * Bloom represents a 256 bit bloom filter.
 */
@interface Web3goBloom : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * GetBytes retrieves the byte representation of the bloom filter.
 */
- (NSData*)getBytes;
/**
 * GetHex retrieves the hex string representation of the bloom filter.
 */
- (NSString*)getHex;
@end

/**
 * BoundContract is the base wrapper object that reflects a contract on the
Ethereum network. It contains a collection of methods that are used by the
higher level contract bindings to operate.
 */
@interface Web3goBoundContract : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * Call invokes the (constant) contract method with params as input values and
sets the output to result.
 */
- (BOOL)call:(Web3goCallOpts*)opts out_:(Web3goInterfaces*)out_ method:(NSString*)method args:(Web3goInterfaces*)args error:(NSError**)error;
/**
 * GetAddress ...
 */
- (Web3goAddress*)getAddress;
/**
 * GetDeployer ...
 */
- (Web3goTransaction*)getDeployer;
/**
 * Transact invokes the (paid) contract method with params as input values.
 */
- (Web3goTransaction*)transact:(Web3goTransactOpts*)opts method:(NSString*)method args:(Web3goInterfaces*)args error:(NSError**)error;
/**
 * Transfer initiates a plain transaction to move funds to the contract, calling
its default method if one is available.
 */
- (Web3goTransaction*)transfer:(Web3goTransactOpts*)opts error:(NSError**)error;
@end

/**
 * CallMsg contains parameters for contract calls.
 */
@interface Web3goCallMsg : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewCallMsg creates an empty contract call parameter list.
 */
- (instancetype)init;
/**
 * GetData ...
 */
- (NSData*)getData;
/**
 * GetFrom ...
 */
- (Web3goAddress*)getFrom;
/**
 * GetGas ...
 */
- (int64_t)getGas;
/**
 * GetGasPrice ...
 */
- (Web3goBigInt*)getGasPrice;
/**
 * GetTo ...
 */
- (Web3goAddress*)getTo;
/**
 * GetValue ...
 */
- (Web3goBigInt*)getValue;
/**
 * SetData ...
 */
- (void)setData:(NSData*)data;
/**
 * SetFrom ...
 */
- (void)setFrom:(Web3goAddress*)address;
/**
 * SetGas ...
 */
- (void)setGas:(int64_t)gas;
/**
 * SetGasPrice ...
 */
- (void)setGasPrice:(Web3goBigInt*)price;
/**
 * SetTo ...
 */
- (void)setTo:(Web3goAddress*)address;
/**
 * SetValue ...
 */
- (void)setValue:(Web3goBigInt*)value;
@end

/**
 * CallOpts is the collection of options to fine tune a contract call request.
 */
@interface Web3goCallOpts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewCallOpts creates a new option set for contract calls.
 */
- (instancetype)init;
/**
 * GetGasLimit ...
 */
- (int64_t)getGasLimit;
/**
 * IsPending ...
 */
- (BOOL)isPending;
/**
 * SetContext ...
 */
- (void)setContext:(Web3goContext*)context;
/**
 * SetGasLimit ...
 */
- (void)setGasLimit:(int64_t)limit;
/**
 * SetPending ...
 */
- (void)setPending:(BOOL)pending;
@end

/**
 * Context carries a deadline, a cancelation signal, and other values across API
boundaries.
 */
@interface Web3goContext : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewContext returns a non-nil, empty Context. It is never canceled, has no
values, and has no deadline. It is typically used by the main function,
initialization, and tests, and as the top-level Context for incoming requests.
 */
- (instancetype)init;
/**
 * WithCancel returns a copy of the original context with cancellation mechanism
included.

Canceling this context releases resources associated with it, so code should
call cancel as soon as the operations running in this Context complete.
 */
- (Web3goContext*)withCancel;
/**
 * WithDeadline returns a copy of the original context with the deadline adjusted
to be no later than the specified time.

Canceling this context releases resources associated with it, so code should
call cancel as soon as the operations running in this Context complete.
 */
- (Web3goContext*)withDeadline:(int64_t)sec nsec:(int64_t)nsec;
/**
 * WithTimeout returns a copy of the original context with the deadline adjusted
to be no later than now + the duration specified.

Canceling this context releases resources associated with it, so code should
call cancel as soon as the operations running in this Context complete.
 */
- (Web3goContext*)withTimeout:(int64_t)nsec;
@end

/**
 * Criteria holds various filter options for inbound messages.
 */
@interface Web3goCriteria : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewCriteria ...
 */
- (instancetype)init:(NSData*)topic;
/**
 * GetMinPow ...
 */
- (double)getMinPow;
/**
 * GetPrivateKeyID ...
 */
- (NSString*)getPrivateKeyID;
/**
 * GetSig ...
 */
- (NSData*)getSig;
/**
 * GetSymKeyID ...
 */
- (NSString*)getSymKeyID;
/**
 * SetMinPow ...
 */
- (void)setMinPow:(double)pow;
/**
 * SetPrivateKeyID ...
 */
- (void)setPrivateKeyID:(NSString*)privateKeyID;
/**
 * SetSig ...
 */
- (void)setSig:(NSData*)sig;
/**
 * SetSymKeyID ...
 */
- (void)setSymKeyID:(NSString*)symKeyID;
@end

/**
 * Enode represents a host on the network.
 */
@interface Web3goEnode : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewEnode parses a node designator.

There are two basic forms of node designators
  - incomplete nodes, which only have the public key (node ID)
  - complete nodes, which contain the public key and IP/Port information

For incomplete nodes, the designator must look like one of these

   enode://<hex node id>
   <hex node id>

For complete nodes, the node ID is encoded in the username portion
of the URL, separated from the host by an @ sign. The hostname can
only be given as an IP address, DNS domain names are not allowed.
The port in the host name section is the TCP listening port. If the
TCP and UDP (discovery) ports differ, the UDP port is specified as
query parameter "discport".

In the following example, the node URL describes
a node with IP address 10.3.58.6, TCP listening port 30303
and UDP discovery port 30301.

   enode://<hex node id>@10.3.58.6:30303?discport=30301
 */
- (instancetype)init:(NSString*)rawurl;
@end

/**
 * Enodes represents a slice of accounts.
 */
@interface Web3goEnodes : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewEnodes creates a slice of uninitialized enodes.
 */
- (instancetype)init:(long)size;
/**
 * NewEnodesEmpty creates an empty slice of Enode values.
 */
- (instancetype)initEmpty;
/**
 * Append adds a new enode element to the end of the slice.
 */
- (void)append:(Web3goEnode*)enode;
/**
 * Get returns the enode at the given index from the slice.
 */
- (Web3goEnode*)get:(long)index error:(NSError**)error;
/**
 * Set sets the enode at the given index in the slice.
 */
- (BOOL)set:(long)index enode:(Web3goEnode*)enode error:(NSError**)error;
/**
 * Size returns the number of enodes in the slice.
 */
- (long)size;
@end

/**
 * EthereumClient provides access to the Ethereum APIs.
 */
@interface Web3goEthereumClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewEthereumClient connects a client to the given URL.
 */
- (instancetype)init:(NSString*)rawurl;
/**
 * CallContract executes a message call transaction, which is directly executed in the VM
of the node, but never mined into the blockchain.

blockNumber selects the block height at which the call runs. It can be <0, in which
case the code is taken from the latest known block. Note that state from very old
blocks might not be available.
 */
- (NSData*)callContract:(Web3goContext*)ctx msg:(Web3goCallMsg*)msg number:(int64_t)number error:(NSError**)error;
/**
 * EstimateGas tries to estimate the gas needed to execute a specific transaction based on
the current pending state of the backend blockchain. There is no guarantee that this is
the true gas limit requirement as other transactions may be added or removed by miners,
but it should provide a basis for setting a reasonable default.
 */
- (BOOL)estimateGas:(Web3goContext*)ctx msg:(Web3goCallMsg*)msg gas:(int64_t*)gas error:(NSError**)error;
/**
 * FilterLogs executes a filter query.
 */
- (Web3goLogs*)filterLogs:(Web3goContext*)ctx query:(Web3goFilterQuery*)query error:(NSError**)error;
/**
 * GetBalanceAt returns the wei balance of the given account.
The block number can be <0, in which case the balance is taken from the latest known block.
 */
- (Web3goBigInt*)getBalanceAt:(Web3goContext*)ctx account:(Web3goAddress*)account number:(int64_t)number error:(NSError**)error;
/**
 * GetBlockByHash returns the given full block.
 */
- (Web3goBlock*)getBlockByHash:(Web3goContext*)ctx hash:(Web3goHash*)hash error:(NSError**)error;
/**
 * GetBlockByNumber returns a block from the current canonical chain. If number is <0, the
latest known block is returned.
 */
- (Web3goBlock*)getBlockByNumber:(Web3goContext*)ctx number:(int64_t)number error:(NSError**)error;
/**
 * GetCodeAt returns the contract code of the given account.
The block number can be <0, in which case the code is taken from the latest known block.
 */
- (NSData*)getCodeAt:(Web3goContext*)ctx account:(Web3goAddress*)account number:(int64_t)number error:(NSError**)error;
/**
 * GetHeaderByHash returns the block header with the given hash.
 */
- (Web3goHeader*)getHeaderByHash:(Web3goContext*)ctx hash:(Web3goHash*)hash error:(NSError**)error;
/**
 * GetHeaderByNumber returns a block header from the current canonical chain. If number is <0,
the latest known header is returned.
 */
- (Web3goHeader*)getHeaderByNumber:(Web3goContext*)ctx number:(int64_t)number error:(NSError**)error;
/**
 * GetNonceAt returns the account nonce of the given account.
The block number can be <0, in which case the nonce is taken from the latest known block.
 */
- (BOOL)getNonceAt:(Web3goContext*)ctx account:(Web3goAddress*)account number:(int64_t)number nonce:(int64_t*)nonce error:(NSError**)error;
/**
 * GetPendingBalanceAt returns the wei balance of the given account in the pending state.
 */
- (Web3goBigInt*)getPendingBalanceAt:(Web3goContext*)ctx account:(Web3goAddress*)account error:(NSError**)error;
/**
 * GetPendingCodeAt returns the contract code of the given account in the pending state.
 */
- (NSData*)getPendingCodeAt:(Web3goContext*)ctx account:(Web3goAddress*)account error:(NSError**)error;
/**
 * GetPendingNonceAt returns the account nonce of the given account in the pending state.
This is the nonce that should be used for the next transaction.
 */
- (BOOL)getPendingNonceAt:(Web3goContext*)ctx account:(Web3goAddress*)account nonce:(int64_t*)nonce error:(NSError**)error;
/**
 * GetPendingStorageAt returns the value of key in the contract storage of the given account in the pending state.
 */
- (NSData*)getPendingStorageAt:(Web3goContext*)ctx account:(Web3goAddress*)account key:(Web3goHash*)key error:(NSError**)error;
/**
 * GetPendingTransactionCount returns the total number of transactions in the pending state.
 */
- (BOOL)getPendingTransactionCount:(Web3goContext*)ctx count:(long*)count error:(NSError**)error;
/**
 * GetStorageAt returns the value of key in the contract storage of the given account.
The block number can be <0, in which case the value is taken from the latest known block.
 */
- (NSData*)getStorageAt:(Web3goContext*)ctx account:(Web3goAddress*)account key:(Web3goHash*)key number:(int64_t)number error:(NSError**)error;
/**
 * GetTransactionByHash returns the transaction with the given hash.
 */
- (Web3goTransaction*)getTransactionByHash:(Web3goContext*)ctx hash:(Web3goHash*)hash error:(NSError**)error;
/**
 * GetTransactionByHashIsPending returns if the transaction pending or not.
 */
- (BOOL)getTransactionByHashIsPending:(Web3goContext*)ctx hash:(Web3goHash*)hash ret0_:(BOOL*)ret0_ error:(NSError**)error;
/**
 * GetTransactionCount returns the total number of transactions in the given block.
 */
- (BOOL)getTransactionCount:(Web3goContext*)ctx hash:(Web3goHash*)hash count:(long*)count error:(NSError**)error;
/**
 * GetTransactionInBlock returns a single transaction at index in the given block.
 */
- (Web3goTransaction*)getTransactionInBlock:(Web3goContext*)ctx hash:(Web3goHash*)hash index:(long)index error:(NSError**)error;
/**
 * GetTransactionReceipt returns the receipt of a transaction by transaction hash.
Note that the receipt is not available for pending transactions.
 */
- (Web3goReceipt*)getTransactionReceipt:(Web3goContext*)ctx hash:(Web3goHash*)hash error:(NSError**)error;
/**
 * GetTransactionSender returns the sender address of a transaction. The transaction must
be included in blockchain at the given block and index.
 */
- (Web3goAddress*)getTransactionSender:(Web3goContext*)ctx tx:(Web3goTransaction*)tx blockhash:(Web3goHash*)blockhash index:(long)index error:(NSError**)error;
/**
 * PendingCallContract executes a message call transaction using the EVM.
The state seen by the contract call is the pending state.
 */
- (NSData*)pendingCallContract:(Web3goContext*)ctx msg:(Web3goCallMsg*)msg error:(NSError**)error;
/**
 * SendTransaction injects a signed transaction into the pending pool for execution.

If the transaction was a contract creation use the TransactionReceipt method to get the
contract address after the transaction has been mined.
 */
- (BOOL)sendTransaction:(Web3goContext*)ctx tx:(Web3goTransaction*)tx error:(NSError**)error;
/**
 * SubscribeFilterLogs subscribes to the results of a streaming filter query.
 */
- (Web3goSubscription*)subscribeFilterLogs:(Web3goContext*)ctx query:(Web3goFilterQuery*)query handler:(id<Web3goFilterLogsHandler>)handler buffer:(long)buffer error:(NSError**)error;
/**
 * SubscribeNewHead subscribes to notifications about the current blockchain head
on the given channel.
 */
- (Web3goSubscription*)subscribeNewHead:(Web3goContext*)ctx handler:(id<Web3goNewHeadHandler>)handler buffer:(long)buffer error:(NSError**)error;
/**
 * SuggestGasPrice retrieves the currently suggested gas price to allow a timely
execution of a transaction.
 */
- (Web3goBigInt*)suggestGasPrice:(Web3goContext*)ctx error:(NSError**)error;
/**
 * SyncProgress retrieves the current progress of the sync algorithm. If there's
no sync currently running, it returns nil.
 */
- (Web3goSyncProgress*)syncProgress:(Web3goContext*)ctx error:(NSError**)error;
@end

/**
 * FilterQuery contains options for contract log filtering.
 */
@interface Web3goFilterQuery : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewFilterQuery creates an empty filter query for contract log filtering.
 */
- (instancetype)init;
/**
 * GetAddresses ...
 */
- (Web3goAddresses*)getAddresses;
/**
 * GetFromBlock ...
 */
- (Web3goBigInt*)getFromBlock;
/**
 * GetToBlock ...
 */
- (Web3goBigInt*)getToBlock;
/**
 * GetTopics ...
 */
- (Web3goTopics*)getTopics;
/**
 * SetAddresses ...
 */
- (void)setAddresses:(Web3goAddresses*)addresses;
/**
 * SetFromBlock ...
 */
- (void)setFromBlock:(Web3goBigInt*)fromBlock;
/**
 * SetToBlock ...
 */
- (void)setToBlock:(Web3goBigInt*)toBlock;
/**
 * SetTopics ...
 */
- (void)setTopics:(Web3goTopics*)topics;
@end

/**
 * GosHash ...
 */
@interface Web3goGosHash : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * Size ...
 */
- (long)size;
/**
 * Sum ...
 */
- (NSData*)sum:(NSData*)b;
/**
 * Write ...
 */
- (BOOL)write:(NSData*)p0 ret0_:(long*)ret0_ error:(NSError**)error;
@end

/**
 * Hash represents the 32 byte Keccak256 hash of arbitrary data.
 */
@interface Web3goHash : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewHashFromBytes converts a slice of bytes to a hash value.
 */
- (instancetype)initFromBytes:(NSData*)binary;
/**
 * NewHashFromHex converts a hex string to a hash value.
 */
- (instancetype)initFromHex:(NSString*)hex;
/**
 * GetBytes retrieves the byte representation of the hash.
 */
- (NSData*)getBytes;
/**
 * GetHex retrieves the hex string representation of the hash.
 */
- (NSString*)getHex;
/**
 * SetBytes sets the specified slice of bytes as the hash value.
 */
- (BOOL)setBytes:(NSData*)hash error:(NSError**)error;
/**
 * SetHex sets the specified hex string as the hash value.
 */
- (BOOL)setHex:(NSString*)hash error:(NSError**)error;
@end

/**
 * Hashes represents a slice of hashes.
 */
@interface Web3goHashes : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewHashes creates a slice of uninitialized Hashes.
 */
- (instancetype)init:(long)size;
/**
 * NewHashesEmpty creates an empty slice of Hashes values.
 */
- (instancetype)initEmpty;
/**
 * Append adds a new Hash element to the end of the slice.
 */
- (void)append:(Web3goHash*)hash;
/**
 * Get returns the hash at the given index from the slice.
 */
- (Web3goHash*)get:(long)index error:(NSError**)error;
/**
 * Set sets the Hash at the given index in the slice.
 */
- (BOOL)set:(long)index hash:(Web3goHash*)hash error:(NSError**)error;
/**
 * Size returns the number of hashes in the slice.
 */
- (long)size;
@end

/**
 * Header represents a block header in the Ethereum blockchain.
 */
@interface Web3goHeader : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewHeaderFromJSON parses a header from a JSON data dump.
 */
- (instancetype)initFromJSON:(NSString*)data;
/**
 * NewHeaderFromRLP parses a header from an RLP data dump.
 */
- (instancetype)initFromRLP:(NSData*)data;
/**
 * EncodeJSON encodes a header into a JSON data dump.
 */
- (NSString*)encodeJSON:(NSError**)error;
/**
 * EncodeRLP encodes a header into an RLP data dump.
 */
- (NSData*)encodeRLP:(NSError**)error;
/**
 * GetBloom ...
 */
- (Web3goBloom*)getBloom;
/**
 * GetCoinbase ...
 */
- (Web3goAddress*)getCoinbase;
/**
 * GetDifficulty ...
 */
- (Web3goBigInt*)getDifficulty;
/**
 * GetExtra ...
 */
- (NSData*)getExtra;
/**
 * GetGasLimit ...
 */
- (int64_t)getGasLimit;
/**
 * GetGasUsed ...
 */
- (int64_t)getGasUsed;
/**
 * GetHash ...
 */
- (Web3goHash*)getHash;
/**
 * GetMixDigest ...
 */
- (Web3goHash*)getMixDigest;
/**
 * GetNonce ...
 */
- (Web3goNonce*)getNonce;
/**
 * GetNumber ...
 */
- (int64_t)getNumber;
/**
 * GetParentHash ...
 */
- (Web3goHash*)getParentHash;
/**
 * GetReceiptHash ...
 */
- (Web3goHash*)getReceiptHash;
/**
 * GetRoot ...
 */
- (Web3goHash*)getRoot;
/**
 * GetTime ...
 */
- (int64_t)getTime;
/**
 * GetTxHash ...
 */
- (Web3goHash*)getTxHash;
/**
 * GetUncleHash ...
 */
- (Web3goHash*)getUncleHash;
@end

/**
 * Headers represents a slice of headers.
 */
@interface Web3goHeaders : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * Get returns the header at the given index from the slice.
 */
- (Web3goHeader*)get:(long)index error:(NSError**)error;
/**
 * Size returns the number of headers in the slice.
 */
- (long)size;
@end

/**
 * HomesteadSigner ...
 */
@interface Web3goHomesteadSigner : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
@end

/**
 * Info represents a diagnostic information about the whisper node.
 */
@interface Web3goInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
@end

/**
 * Interface represents a wrapped version of Go's interface{}, with the capacity
to store arbitrary data types.

Since it's impossible to get the arbitrary-ness converted between Go and mobile
platforms, we're using explicit getters and setters for the conversions. There
is of course no point in enumerating everything, just enough to support the
contract bindins requiring client side generated code.
 */
@interface Web3goInterface : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewInterface creates a new empty interface that can be used to pass around
generic types.
 */
- (instancetype)init;
/**
 * GetAddress ...
 */
- (Web3goAddress*)getAddress;
/**
 * GetAddresses ...
 */
- (Web3goAddresses*)getAddresses;
/**
 * GetBigInt ...
 */
- (Web3goBigInt*)getBigInt;
/**
 * GetBigInts ...
 */
- (Web3goBigInts*)getBigInts;
/**
 * GetBinary ...
 */
- (NSData*)getBinary;
/**
 * GetBool ...
 */
- (BOOL)getBool;
/**
 * GetHash ...
 */
- (Web3goHash*)getHash;
/**
 * GetHashes ...
 */
- (Web3goHashes*)getHashes;
/**
 * GetInt16 ...
 */
- (int16_t)getInt16;
/**
 * GetInt32 ...
 */
- (int32_t)getInt32;
/**
 * GetInt64 ...
 */
- (int64_t)getInt64;
/**
 * GetInt8 ...
 */
- (int8_t)getInt8;
/**
 * GetString ...
 */
- (NSString*)getString;
/**
 * GetStrings ...
 */
- (Web3goStrings*)getStrings;
/**
 * GetUint16 ...
 */
- (Web3goBigInt*)getUint16;
/**
 * GetUint32 ...
 */
- (Web3goBigInt*)getUint32;
/**
 * GetUint64 ...
 */
- (Web3goBigInt*)getUint64;
/**
 * GetUint8 ...
 */
- (Web3goBigInt*)getUint8;
/**
 * SetAddress ...
 */
- (void)setAddress:(Web3goAddress*)address;
/**
 * SetAddresses ...
 */
- (void)setAddresses:(Web3goAddresses*)addrs;
/**
 * SetBigInt ...
 */
- (void)setBigInt:(Web3goBigInt*)bigint;
/**
 * SetBigInts ...
 */
- (void)setBigInts:(Web3goBigInts*)bigints;
/**
 * SetBinary ...
 */
- (void)setBinary:(NSData*)binary;
/**
 * SetBool ...
 */
- (void)setBool:(BOOL)b;
/**
 * SetDefaultAddress ...
 */
- (void)setDefaultAddress;
/**
 * SetDefaultAddresses ...
 */
- (void)setDefaultAddresses;
/**
 * SetDefaultBigInt ...
 */
- (void)setDefaultBigInt;
/**
 * SetDefaultBigInts ...
 */
- (void)setDefaultBigInts;
/**
 * SetDefaultBinaries ...
 */
- (void)setDefaultBinaries;
/**
 * SetDefaultBinary ...
 */
- (void)setDefaultBinary;
/**
 * SetDefaultBool ...
 */
- (void)setDefaultBool;
/**
 * SetDefaultBools ...
 */
- (void)setDefaultBools;
/**
 * SetDefaultHash ...
 */
- (void)setDefaultHash;
/**
 * SetDefaultHashes ...
 */
- (void)setDefaultHashes;
/**
 * SetDefaultInt16 ...
 */
- (void)setDefaultInt16;
/**
 * SetDefaultInt32 ...
 */
- (void)setDefaultInt32;
/**
 * SetDefaultInt64 ...
 */
- (void)setDefaultInt64;
/**
 * SetDefaultInt8 ...
 */
- (void)setDefaultInt8;
/**
 * SetDefaultString ...
 */
- (void)setDefaultString;
/**
 * SetDefaultStrings ...
 */
- (void)setDefaultStrings;
/**
 * SetDefaultUint16 ...
 */
- (void)setDefaultUint16;
/**
 * SetDefaultUint32 ...
 */
- (void)setDefaultUint32;
/**
 * SetDefaultUint64 ...
 */
- (void)setDefaultUint64;
/**
 * SetDefaultUint8 ...
 */
- (void)setDefaultUint8;
/**
 * SetHash ...
 */
- (void)setHash:(Web3goHash*)hash;
/**
 * SetHashes ...
 */
- (void)setHashes:(Web3goHashes*)hashes;
/**
 * SetInt16 ...
 */
- (void)setInt16:(int16_t)n;
/**
 * SetInt32 ...
 */
- (void)setInt32:(int32_t)n;
/**
 * SetInt64 ...
 */
- (void)setInt64:(int64_t)n;
/**
 * SetInt8 ...
 */
- (void)setInt8:(int8_t)n;
/**
 * SetString ...
 */
- (void)setString:(NSString*)str;
/**
 * SetStrings ...
 */
- (void)setStrings:(Web3goStrings*)strs;
/**
 * SetUint16 ...
 */
- (void)setUint16:(Web3goBigInt*)bigint;
/**
 * SetUint32 ...
 */
- (void)setUint32:(Web3goBigInt*)bigint;
/**
 * SetUint64 ...
 */
- (void)setUint64:(Web3goBigInt*)bigint;
/**
 * SetUint8 ...
 */
- (void)setUint8:(Web3goBigInt*)bigint;
@end

/**
 * Interfaces is a slices of wrapped generic objects.
 */
@interface Web3goInterfaces : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewInterfaces creates a slice of uninitialized interfaces.
 */
- (instancetype)init:(long)size;
/**
 * Get returns the bigint at the given index from the slice.
 */
- (Web3goInterface*)get:(long)index error:(NSError**)error;
/**
 * Set sets the big int at the given index in the slice.
 */
- (BOOL)set:(long)index object:(Web3goInterface*)object error:(NSError**)error;
/**
 * Size returns the number of interfaces in the slice.
 */
- (long)size;
@end

/**
 * KeyStore manages a key storage directory on disk.
 */
@interface Web3goKeyStore : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewKeyStore creates a keystore for the given directory.
 */
- (instancetype)init:(NSString*)keydir scryptN:(long)scryptN scryptP:(long)scryptP;
/**
 * DeleteAccount deletes the key matched by account if the passphrase is correct.
If a contains no filename, the address must match a unique key.
 */
- (BOOL)deleteAccount:(Web3goAccount*)account passphrase:(NSString*)passphrase error:(NSError**)error;
/**
 * ExportKey exports as a JSON key, encrypted with newPassphrase.
 */
- (NSData*)exportKey:(Web3goAccount*)account passphrase:(NSString*)passphrase newPassphrase:(NSString*)newPassphrase error:(NSError**)error;
/**
 * GetAccounts returns all key files present in the directory.
 */
- (Web3goAccounts*)getAccounts;
/**
 * HasAddress reports whether a key with the given address is present.
 */
- (BOOL)hasAddress:(Web3goAddress*)address;
/**
 * ImportECDSAKey stores the given encrypted JSON key into the key directory.
 */
- (Web3goAccount*)importECDSAKey:(NSData*)key passphrase:(NSString*)passphrase error:(NSError**)error;
/**
 * ImportKey stores the given encrypted JSON key into the key directory.
 */
- (Web3goAccount*)importKey:(NSData*)keyJSON passphrase:(NSString*)passphrase newPassphrase:(NSString*)newPassphrase error:(NSError**)error;
/**
 * ImportPreSaleKey decrypts the given Ethereum presale wallet and stores
a key file in the key directory. The key file is encrypted with the same passphrase.
 */
- (Web3goAccount*)importPreSaleKey:(NSData*)keyJSON passphrase:(NSString*)passphrase error:(NSError**)error;
/**
 * Lock removes the private key with the given address from memory.
 */
- (BOOL)lock:(Web3goAddress*)address error:(NSError**)error;
/**
 * NewAccount generates a new key and stores it into the key directory,
encrypting it with the passphrase.
 */
- (Web3goAccount*)newAccount:(NSString*)passphrase error:(NSError**)error;
/**
 * SignHash calculates a ECDSA signature for the given hash. The produced signature
is in the [R || S || V] format where V is 0 or 1.
 */
- (NSData*)signHash:(Web3goAddress*)address hash:(NSData*)hash error:(NSError**)error;
/**
 * SignHashPassphrase signs hash if the private key matching the given address can
be decrypted with the given passphrase. The produced signature is in the
[R || S || V] format where V is 0 or 1.
 */
- (NSData*)signHashPassphrase:(Web3goAccount*)account passphrase:(NSString*)passphrase hash:(NSData*)hash error:(NSError**)error;
/**
 * SignTx signs the given transaction with the requested account.
 */
- (Web3goTransaction*)signTx:(Web3goAccount*)account tx:(Web3goTransaction*)tx chainID:(Web3goBigInt*)chainID error:(NSError**)error;
/**
 * SignTxPassphrase signs the transaction if the private key matching the
given address can be decrypted with the given passphrase.
 */
- (Web3goTransaction*)signTxPassphrase:(Web3goAccount*)account passphrase:(NSString*)passphrase tx:(Web3goTransaction*)tx chainID:(Web3goBigInt*)chainID error:(NSError**)error;
/**
 * TimedUnlock unlocks the given account with the passphrase. The account stays
unlocked for the duration of timeout (nanoseconds). A timeout of 0 unlocks the
account until the program exits. The account must match a unique key file.

If the account address is already unlocked for a duration, TimedUnlock extends or
shortens the active unlock timeout. If the address was previously unlocked
indefinitely the timeout is not altered.
 */
- (BOOL)timedUnlock:(Web3goAccount*)account passphrase:(NSString*)passphrase timeout:(int64_t)timeout error:(NSError**)error;
/**
 * Unlock unlocks the given account indefinitely.
 */
- (BOOL)unlock:(Web3goAccount*)account passphrase:(NSString*)passphrase error:(NSError**)error;
/**
 * UpdateAccount changes the passphrase of an existing account.
 */
- (BOOL)updateAccount:(Web3goAccount*)account passphrase:(NSString*)passphrase newPassphrase:(NSString*)newPassphrase error:(NSError**)error;
@end

/**
 * Log represents a contract log event. These events are generated by the LOG
opcode and stored/indexed by the node.
 */
@interface Web3goLog : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * GetAddress ...
 */
- (Web3goAddress*)getAddress;
/**
 * GetBlockHash ...
 */
- (Web3goHash*)getBlockHash;
/**
 * GetBlockNumber ...
 */
- (int64_t)getBlockNumber;
/**
 * GetData ...
 */
- (NSData*)getData;
/**
 * GetIndex ...
 */
- (long)getIndex;
/**
 * GetTopics ...
 */
- (Web3goHashes*)getTopics;
/**
 * GetTxHash ...
 */
- (Web3goHash*)getTxHash;
/**
 * GetTxIndex ...
 */
- (long)getTxIndex;
@end

/**
 * Logs represents a slice of VM logs.
 */
@interface Web3goLogs : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * Get returns the log at the given index from the slice.
 */
- (Web3goLog*)get:(long)index error:(NSError**)error;
/**
 * Size returns the number of logs in the slice.
 */
- (long)size;
@end

/**
 * Message represents a whisper message.
 */
@interface Web3goMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * GetDst ...
 */
- (NSData*)getDst;
/**
 * GetHash ...
 */
- (NSData*)getHash;
/**
 * GetPayload ...
 */
- (NSData*)getPayload;
/**
 * GetPoW ...
 */
- (double)getPoW;
/**
 * GetSig ...
 */
- (NSData*)getSig;
/**
 * GetTTL ...
 */
- (int64_t)getTTL;
/**
 * GetTimestamp ...
 */
- (int64_t)getTimestamp;
@end

/**
 * Messages represents an array of messages.
 */
@interface Web3goMessages : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * Get returns the message at the given index from the slice.
 */
- (Web3goMessage*)get:(long)index error:(NSError**)error;
/**
 * Size returns the number of messages in the slice.
 */
- (long)size;
@end

/**
 * NewMessage represents a new whisper message that is posted through the RPC.
 */
@interface Web3goNewMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewNewMessage ...
 */
- (instancetype)init;
/**
 * GetPayload ...
 */
- (NSData*)getPayload;
/**
 * GetPowTarget ...
 */
- (double)getPowTarget;
/**
 * GetPowTime ...
 */
- (int64_t)getPowTime;
/**
 * GetPublicKey ...
 */
- (NSData*)getPublicKey;
/**
 * GetSig ...
 */
- (NSString*)getSig;
/**
 * GetSymKeyID ...
 */
- (NSString*)getSymKeyID;
/**
 * GetTTL ...
 */
- (int64_t)getTTL;
/**
 * GetTargetPeer ...
 */
- (NSString*)getTargetPeer;
/**
 * GetTopic ...
 */
- (NSData*)getTopic;
/**
 * SetPayload ...
 */
- (void)setPayload:(NSData*)payload;
/**
 * SetPowTarget ...
 */
- (void)setPowTarget:(double)powTarget;
/**
 * SetPowTime ...
 */
- (void)setPowTime:(int64_t)powTime;
/**
 * SetPublicKey ...
 */
- (void)setPublicKey:(NSData*)publicKey;
/**
 * SetSig ...
 */
- (void)setSig:(NSString*)sig;
/**
 * SetSymKeyID ...
 */
- (void)setSymKeyID:(NSString*)symKeyID;
/**
 * SetTTL ...
 */
- (void)setTTL:(int64_t)ttl;
/**
 * SetTargetPeer ...
 */
- (void)setTargetPeer:(NSString*)targetPeer;
/**
 * SetTopic ...
 */
- (void)setTopic:(NSData*)topic;
@end

/**
 * Node represents a Geth Ethereum node instance.
 */
@interface Web3goNode : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewNode creates and configures a new Geth node.
 */
- (instancetype)init:(NSString*)datadir config:(Web3goNodeConfig*)config;
/**
 * GetEthereumClient retrieves a client to access the Ethereum subsystem.
 */
- (Web3goEthereumClient*)getEthereumClient:(NSError**)error;
/**
 * GetNodeInfo gathers and returns a collection of metadata known about the host.
 */
- (Web3goNodeInfo*)getNodeInfo;
/**
 * GetPeersInfo returns an array of metadata objects describing connected peers.
 */
- (Web3goPeerInfos*)getPeersInfo;
/**
 * Start creates a live P2P node and starts running it.
 */
- (BOOL)start:(NSError**)error;
/**
 * Stop terminates a running node along with all it's services. If the node was
not started, an error is returned.
 */
- (BOOL)stop:(NSError**)error;
@end

/**
 * NodeConfig represents the collection of configuration values to fine tune the Geth
node embedded into a mobile process. The available values are a subset of the
entire API provided by go-ethereum to reduce the maintenance surface and dev
complexity.
 */
@interface Web3goNodeConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewNodeConfig creates a new node option set, initialized to the default values.
 */
- (instancetype)init;
/**
 * Bootstrap nodes used to establish connectivity with the rest of the network.
 */
@property (nonatomic) Web3goEnodes* bootstrapNodes;
/**
 * MaxPeers is the maximum number of peers that can be connected. If this is
set to zero, then only the configured static and trusted peers can connect.
 */
@property (nonatomic) long maxPeers;
/**
 * EthereumEnabled specifies whether the node should run the Ethereum protocol.
 */
@property (nonatomic) BOOL ethereumEnabled;
/**
 * EthereumNetworkID is the network identifier used by the Ethereum protocol to
decide if remote peers should be accepted or not.
 */
@property (nonatomic) int64_t ethereumNetworkID;
/**
 * EthereumGenesis is the genesis JSON to use to seed the blockchain with. An
empty genesis state is equivalent to using the mainnet's state.
 */
@property (nonatomic) NSString* ethereumGenesis;
/**
 * EthereumDatabaseCache is the system memory in MB to allocate for database caching.
A minimum of 16MB is always reserved.
 */
@property (nonatomic) long ethereumDatabaseCache;
/**
 * EthereumNetStats is a netstats connection string to use to report various
chain, transaction and node stats to a monitoring server.

It has the form "nodename:secret@host:port"
 */
@property (nonatomic) NSString* ethereumNetStats;
/**
 * WhisperEnabled specifies whether the node should run the Whisper protocol.
 */
@property (nonatomic) BOOL whisperEnabled;
/**
 * Listening address of pprof server.
 */
@property (nonatomic) NSString* pprofAddress;
@end

/**
 * NodeInfo represents pi short summary of the information known about the host.
 */
@interface Web3goNodeInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * GetDiscoveryPort ...
 */
- (long)getDiscoveryPort;
/**
 * GetEnode ...
 */
- (NSString*)getEnode;
/**
 * GetID ...
 */
- (NSString*)getID;
/**
 * GetIP ...
 */
- (NSString*)getIP;
/**
 * GetListenerAddress ...
 */
- (NSString*)getListenerAddress;
/**
 * GetListenerPort ...
 */
- (long)getListenerPort;
/**
 * GetName ...
 */
- (NSString*)getName;
/**
 * GetProtocols ...
 */
- (Web3goStrings*)getProtocols;
@end

/**
 * A Nonce is a 64-bit hash which proves (combined with the mix-hash) that
a sufficient amount of computation has been carried out on a block.
 */
@interface Web3goNonce : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * GetBytes retrieves the byte representation of the block nonce.
 */
- (NSData*)getBytes;
/**
 * GetHex retrieves the hex string representation of the block nonce.
 */
- (NSString*)getHex;
@end

/**
 * PeerInfo represents pi short summary of the information known about pi connected peer.
 */
@interface Web3goPeerInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * GetCaps ...
 */
- (Web3goStrings*)getCaps;
/**
 * GetID ...
 */
- (NSString*)getID;
/**
 * GetLocalAddress ...
 */
- (NSString*)getLocalAddress;
/**
 * GetName ...
 */
- (NSString*)getName;
/**
 * GetRemoteAddress ...
 */
- (NSString*)getRemoteAddress;
@end

/**
 * PeerInfos represents a slice of infos about remote peers.
 */
@interface Web3goPeerInfos : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * Get returns the peer info at the given index from the slice.
 */
- (Web3goPeerInfo*)get:(long)index error:(NSError**)error;
/**
 * Size returns the number of peer info entries in the slice.
 */
- (long)size;
@end

/**
 * PrivateKey ...
 */
@interface Web3goPrivateKey : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (Web3goPublicKey*)public;
@end

/**
 * PublicKey ...
 */
@interface Web3goPublicKey : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
@end

/**
 * Receipt represents the results of a transaction.
 */
@interface Web3goReceipt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewReceiptFromJSON parses a transaction receipt from a JSON data dump.
 */
- (instancetype)initFromJSON:(NSString*)data;
/**
 * NewReceiptFromRLP parses a transaction receipt from an RLP data dump.
 */
- (instancetype)initFromRLP:(NSData*)data;
/**
 * EncodeJSON encodes a transaction receipt into a JSON data dump.
 */
- (NSString*)encodeJSON:(NSError**)error;
/**
 * EncodeRLP encodes a transaction receipt into an RLP data dump.
 */
- (NSData*)encodeRLP:(NSError**)error;
/**
 * GetBloom ...
 */
- (Web3goBloom*)getBloom;
/**
 * GetContractAddress ...
 */
- (Web3goAddress*)getContractAddress;
/**
 * GetCumulativeGasUsed ...
 */
- (int64_t)getCumulativeGasUsed;
/**
 * GetGasUsed ...
 */
- (int64_t)getGasUsed;
/**
 * GetLogs ...
 */
- (Web3goLogs*)getLogs;
/**
 * GetPostState ...
 */
- (NSData*)getPostState;
/**
 * GetStatus ...
 */
- (long)getStatus;
/**
 * GetTxHash ...
 */
- (Web3goHash*)getTxHash;
@end

/**
 * Signer2 ...
 */
@interface Web3goSigner2 : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
@end

/**
 * Strings represents s slice of strs.
 */
@interface Web3goStrings : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * Get returns the string at the given index from the slice.
 */
- (NSString*)get:(long)index error:(NSError**)error;
/**
 * Set sets the string at the given index in the slice.
 */
- (BOOL)set:(long)index str:(NSString*)str error:(NSError**)error;
/**
 * Size returns the number of strs in the slice.
 */
- (long)size;
/**
 * String implements the Stringer interface.
 */
- (NSString*)string;
@end

/**
 * Subscription represents an event subscription where events are
delivered on a data channel.
 */
@interface Web3goSubscription : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * Unsubscribe cancels the sending of events to the data channel
and closes the error channel.
 */
- (void)unsubscribe;
@end

/**
 * SyncProgress gives progress indications when the node is synchronising with
the Ethereum network.
 */
@interface Web3goSyncProgress : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * GetCurrentBlock ...
 */
- (int64_t)getCurrentBlock;
/**
 * GetHighestBlock ...
 */
- (int64_t)getHighestBlock;
/**
 * GetKnownStates ...
 */
- (int64_t)getKnownStates;
/**
 * GetPulledStates ...
 */
- (int64_t)getPulledStates;
/**
 * GetStartingBlock ...
 */
- (int64_t)getStartingBlock;
@end

/**
 * Topics is a set of topic lists to filter events with.
 */
@interface Web3goTopics : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewTopics creates a slice of uninitialized Topics.
 */
- (instancetype)init:(long)size;
/**
 * NewTopicsEmpty creates an empty slice of Topics values.
 */
- (instancetype)initEmpty;
/**
 * Append adds a new topic list to the end of the slice.
 */
- (void)append:(Web3goHashes*)topics;
/**
 * Get returns the topic list at the given index from the slice.
 */
- (Web3goHashes*)get:(long)index error:(NSError**)error;
/**
 * Set sets the topic list at the given index in the slice.
 */
- (BOOL)set:(long)index topics:(Web3goHashes*)topics error:(NSError**)error;
/**
 * Size returns the number of topic lists inside the set
 */
- (long)size;
@end

/**
 * TransactOpts is the collection of authorization data required to create a
valid Ethereum transaction.
 */
@interface Web3goTransactOpts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * GetFrom ...
 */
- (Web3goAddress*)getFrom;
/**
 * GetGasLimit ...
 */
- (int64_t)getGasLimit;
/**
 * GetGasPrice ...
 */
- (Web3goBigInt*)getGasPrice;
/**
 * GetNonce ...
 */
- (int64_t)getNonce;
/**
 * GetValue ...
 */
- (Web3goBigInt*)getValue;
/**
 * SetContext ...
 */
- (void)setContext:(Web3goContext*)context;
/**
 * SetFrom ...
 */
- (void)setFrom:(Web3goAddress*)from;
/**
 * SetGasLimit ...
 */
- (void)setGasLimit:(int64_t)limit;
/**
 * SetGasPrice ...
 */
- (void)setGasPrice:(Web3goBigInt*)price;
/**
 * SetNonce ...
 */
- (void)setNonce:(int64_t)nonce;
/**
 * SetSigner ...
 */
- (void)setSigner:(id<Web3goSigner>)s;
/**
 * SetValue ...
 */
- (void)setValue:(Web3goBigInt*)value;
@end

/**
 * Transaction represents a single Ethereum transaction.
 */
@interface Web3goTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewTransaction creates a new transaction with the given properties.
 */
- (instancetype)init:(int64_t)nonce to:(Web3goAddress*)to amount:(Web3goBigInt*)amount gasLimit:(int64_t)gasLimit gasPrice:(Web3goBigInt*)gasPrice data:(NSData*)data;
/**
 * NewTransactionFromJSON parses a transaction from a JSON data dump.
 */
- (instancetype)initFromJSON:(NSString*)data;
/**
 * NewTransactionFromRLP parses a transaction from an RLP data dump.
 */
- (instancetype)initFromRLP:(NSData*)data;
/**
 * EncodeJSON encodes a transaction into a JSON data dump.
 */
- (NSString*)encodeJSON:(NSError**)error;
/**
 * EncodeRLP encodes a transaction into an RLP data dump.
 */
- (NSData*)encodeRLP:(NSError**)error;
/**
 * GetCost ...
 */
- (Web3goBigInt*)getCost;
/**
 * GetData ...
 */
- (NSData*)getData;
/**
 * GetFrom ...
Deprecated: use EthereumClient.TransactionSender
 */
- (Web3goAddress*)getFrom:(Web3goBigInt*)chainID error:(NSError**)error;
/**
 * GetGas ...
 */
- (int64_t)getGas;
/**
 * GetGasPrice ...
 */
- (Web3goBigInt*)getGasPrice;
/**
 * GetHash ...
 */
- (Web3goHash*)getHash;
/**
 * GetNonce ...
 */
- (int64_t)getNonce;
/**
 * GetSigHash ...
Deprecated: GetSigHash cannot know which signer to use.
 */
- (Web3goHash*)getSigHash;
/**
 * GetTo ...
 */
- (Web3goAddress*)getTo;
/**
 * GetValue ...
 */
- (Web3goBigInt*)getValue;
/**
 * WithSignature ...
 */
- (Web3goTransaction*)withSignature:(NSData*)sig chainID:(Web3goBigInt*)chainID error:(NSError**)error;
@end

/**
 * Transactions represents a slice of transactions.
 */
@interface Web3goTransactions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * Get returns the transaction at the given index from the slice.
 */
- (Web3goTransaction*)get:(long)index error:(NSError**)error;
/**
 * Size returns the number of transactions in the slice.
 */
- (long)size;
@end

/**
 * LightScryptN is the N parameter of Scrypt encryption algorithm, using 4MB
memory and taking approximately 100ms CPU time on a modern processor.
 */
FOUNDATION_EXPORT const long Web3goLightScryptN;
/**
 * LightScryptP is the P parameter of Scrypt encryption algorithm, using 4MB
memory and taking approximately 100ms CPU time on a modern processor.
 */
FOUNDATION_EXPORT const long Web3goLightScryptP;
/**
 * StandardScryptN is the N parameter of Scrypt encryption algorithm, using 256MB
memory and taking approximately 1s CPU time on a modern processor.
 */
FOUNDATION_EXPORT const long Web3goStandardScryptN;
/**
 * StandardScryptP is the P parameter of Scrypt encryption algorithm, using 256MB
memory and taking approximately 1s CPU time on a modern processor.
 */
FOUNDATION_EXPORT const long Web3goStandardScryptP;

/**
 * BindContract creates a low level contract interface through which calls and
transactions may be made through.
 */
FOUNDATION_EXPORT Web3goBoundContract* Web3goBindContract(Web3goAddress* address, NSString* abiJSON, Web3goEthereumClient* client, NSError** error);

/**
 * CompressPubkey ...
 */
FOUNDATION_EXPORT NSData* Web3goCompressPubkey(Web3goPublicKey* wpubkey);

/**
 * CreateAddress ...
 */
FOUNDATION_EXPORT Web3goAddress* Web3goCreateAddress(Web3goAddress* wb, int64_t wnonce);

/**
 * Decode ...
 */
FOUNDATION_EXPORT NSData* Web3goDecode(NSString* input, NSError** error);

/**
 * DecodeBig ...
 */
FOUNDATION_EXPORT Web3goBigInt* Web3goDecodeBig(NSString* s, NSError** error);

/**
 * DecompressPubkey ...
 */
FOUNDATION_EXPORT Web3goPublicKey* Web3goDecompressPubkey(NSData* pubkey, NSError** error);

/**
 * DeployContract deploys a contract onto the Ethereum blockchain and binds the
deployment address with a wrapper.
 */
FOUNDATION_EXPORT Web3goBoundContract* Web3goDeployContract(Web3goTransactOpts* opts, NSString* abiJSON, NSData* bytecode, Web3goEthereumClient* client, Web3goInterfaces* args, NSError** error);

/**
 * Ecrecover ...
 */
FOUNDATION_EXPORT NSData* Web3goEcrecover(NSData* hash, NSData* sig, NSError** error);

/**
 * Encode ...
 */
FOUNDATION_EXPORT NSString* Web3goEncode(NSData* b);

/**
 * EncodeBig ...
 */
FOUNDATION_EXPORT NSString* Web3goEncodeBig(Web3goBigInt* wbigint);

/**
 * FoundationBootnodes returns the enode URLs of the P2P bootstrap nodes operated
by the foundation running the V5 discovery protocol.
 */
FOUNDATION_EXPORT Web3goEnodes* Web3goFoundationBootnodes(void);

/**
 * FromECDSA ...
 */
FOUNDATION_EXPORT NSData* Web3goFromECDSA(Web3goPrivateKey* priv);

/**
 * FromECDSAPub ...
 */
FOUNDATION_EXPORT NSData* Web3goFromECDSAPub(Web3goPublicKey* pub);

/**
 * GenerateKey ...
 */
FOUNDATION_EXPORT Web3goPrivateKey* Web3goGenerateKey(NSError** error);

/**
 * HexToECDSA ...
 */
FOUNDATION_EXPORT Web3goPrivateKey* Web3goHexToECDSA(NSString* hexkey, NSError** error);

/**
 * Keccak256 ...
TODO: input type of original Keccak256 is ...[]byte.
      K changed to []byte.
      have to check if this modification is fine or not.
 */
FOUNDATION_EXPORT NSData* Web3goKeccak256(NSData* data);

/**
 * Keccak256Hash ...
TODO: input type of original Keccak256Hash is ...[]byte.
      K changed to []byte.
      have to check if this modification is fine or not.
 */
FOUNDATION_EXPORT Web3goHash* Web3goKeccak256Hash(NSData* data);

/**
 * Keccak512 ...
TODO: input type of original Keccak512 is ...[]byte.
      K changed to []byte.
      have to check if this modification is fine or not.
 */
FOUNDATION_EXPORT NSData* Web3goKeccak512(NSData* data);

/**
 * LeftPadBytes ...
 */
FOUNDATION_EXPORT NSData* Web3goLeftPadBytes(NSData* slice, long l);

/**
 * LoadECDSA ...
 */
FOUNDATION_EXPORT Web3goPrivateKey* Web3goLoadECDSA(NSString* file, NSError** error);

/**
 * MainnetGenesis returns the JSON spec to use for the main Ethereum network. It
is actually empty since that defaults to the hard coded binary genesis block.
 */
FOUNDATION_EXPORT NSString* Web3goMainnetGenesis(void);

/**
 * MustDecode ...
 */
FOUNDATION_EXPORT NSData* Web3goMustDecode(NSString* s);

/**
 * MustDecodeBig ...
 */
FOUNDATION_EXPORT Web3goBigInt* Web3goMustDecodeBig(NSString* s);

/**
 * New256 ...
 */
FOUNDATION_EXPORT Web3goGosHash* Web3goNew256(void);

/**
 * NewAddressFromBytes converts a slice of bytes to a hash value.
 */
FOUNDATION_EXPORT Web3goAddress* Web3goNewAddressFromBytes(NSData* binary, NSError** error);

/**
 * NewAddressFromHex converts a hex string to a address value.
 */
FOUNDATION_EXPORT Web3goAddress* Web3goNewAddressFromHex(NSString* hex, NSError** error);

/**
 * NewAddresses creates a slice of uninitialized addresses.
 */
FOUNDATION_EXPORT Web3goAddresses* Web3goNewAddresses(long size);

/**
 * NewAddressesEmpty creates an empty slice of Addresses values.
 */
FOUNDATION_EXPORT Web3goAddresses* Web3goNewAddressesEmpty(void);

/**
 * NewBigInt allocates and returns a new BigInt set to x.
 */
FOUNDATION_EXPORT Web3goBigInt* Web3goNewBigInt(int64_t x);

/**
 * NewBigInts creates a slice of uninitialized big numbers.
 */
FOUNDATION_EXPORT Web3goBigInts* Web3goNewBigInts(long size);

/**
 * NewBlockFromJSON parses a block from a JSON data dump.
 */
FOUNDATION_EXPORT Web3goBlock* Web3goNewBlockFromJSON(NSString* data, NSError** error);

/**
 * NewBlockFromRLP parses a block from an RLP data dump.
 */
FOUNDATION_EXPORT Web3goBlock* Web3goNewBlockFromRLP(NSData* data, NSError** error);

/**
 * NewCallMsg creates an empty contract call parameter list.
 */
FOUNDATION_EXPORT Web3goCallMsg* Web3goNewCallMsg(void);

/**
 * NewCallOpts creates a new option set for contract calls.
 */
FOUNDATION_EXPORT Web3goCallOpts* Web3goNewCallOpts(void);

/**
 * NewContext returns a non-nil, empty Context. It is never canceled, has no
values, and has no deadline. It is typically used by the main function,
initialization, and tests, and as the top-level Context for incoming requests.
 */
FOUNDATION_EXPORT Web3goContext* Web3goNewContext(void);

/**
 * NewCriteria ...
 */
FOUNDATION_EXPORT Web3goCriteria* Web3goNewCriteria(NSData* topic);

/**
 * NewEnode parses a node designator.

There are two basic forms of node designators
  - incomplete nodes, which only have the public key (node ID)
  - complete nodes, which contain the public key and IP/Port information

For incomplete nodes, the designator must look like one of these

   enode://<hex node id>
   <hex node id>

For complete nodes, the node ID is encoded in the username portion
of the URL, separated from the host by an @ sign. The hostname can
only be given as an IP address, DNS domain names are not allowed.
The port in the host name section is the TCP listening port. If the
TCP and UDP (discovery) ports differ, the UDP port is specified as
query parameter "discport".

In the following example, the node URL describes
a node with IP address 10.3.58.6, TCP listening port 30303
and UDP discovery port 30301.

   enode://<hex node id>@10.3.58.6:30303?discport=30301
 */
FOUNDATION_EXPORT Web3goEnode* Web3goNewEnode(NSString* rawurl, NSError** error);

/**
 * NewEnodes creates a slice of uninitialized enodes.
 */
FOUNDATION_EXPORT Web3goEnodes* Web3goNewEnodes(long size);

/**
 * NewEnodesEmpty creates an empty slice of Enode values.
 */
FOUNDATION_EXPORT Web3goEnodes* Web3goNewEnodesEmpty(void);

/**
 * NewEthereumClient connects a client to the given URL.
 */
FOUNDATION_EXPORT Web3goEthereumClient* Web3goNewEthereumClient(NSString* rawurl, NSError** error);

/**
 * NewFilterQuery creates an empty filter query for contract log filtering.
 */
FOUNDATION_EXPORT Web3goFilterQuery* Web3goNewFilterQuery(void);

/**
 * NewHashFromBytes converts a slice of bytes to a hash value.
 */
FOUNDATION_EXPORT Web3goHash* Web3goNewHashFromBytes(NSData* binary, NSError** error);

/**
 * NewHashFromHex converts a hex string to a hash value.
 */
FOUNDATION_EXPORT Web3goHash* Web3goNewHashFromHex(NSString* hex, NSError** error);

/**
 * NewHashes creates a slice of uninitialized Hashes.
 */
FOUNDATION_EXPORT Web3goHashes* Web3goNewHashes(long size);

/**
 * NewHashesEmpty creates an empty slice of Hashes values.
 */
FOUNDATION_EXPORT Web3goHashes* Web3goNewHashesEmpty(void);

/**
 * NewHeaderFromJSON parses a header from a JSON data dump.
 */
FOUNDATION_EXPORT Web3goHeader* Web3goNewHeaderFromJSON(NSString* data, NSError** error);

/**
 * NewHeaderFromRLP parses a header from an RLP data dump.
 */
FOUNDATION_EXPORT Web3goHeader* Web3goNewHeaderFromRLP(NSData* data, NSError** error);

/**
 * NewHomesteadSigner ...
 */
FOUNDATION_EXPORT Web3goSigner2* Web3goNewHomesteadSigner(void);

/**
 * NewInterface creates a new empty interface that can be used to pass around
generic types.
 */
FOUNDATION_EXPORT Web3goInterface* Web3goNewInterface(void);

/**
 * NewInterfaces creates a slice of uninitialized interfaces.
 */
FOUNDATION_EXPORT Web3goInterfaces* Web3goNewInterfaces(long size);

/**
 * NewKeyStore creates a keystore for the given directory.
 */
FOUNDATION_EXPORT Web3goKeyStore* Web3goNewKeyStore(NSString* keydir, long scryptN, long scryptP);

/**
 * NewNewMessage ...
 */
FOUNDATION_EXPORT Web3goNewMessage* Web3goNewNewMessage(void);

/**
 * NewNode creates and configures a new Geth node.
 */
FOUNDATION_EXPORT Web3goNode* Web3goNewNode(NSString* datadir, Web3goNodeConfig* config, NSError** error);

/**
 * NewNodeConfig creates a new node option set, initialized to the default values.
 */
FOUNDATION_EXPORT Web3goNodeConfig* Web3goNewNodeConfig(void);

/**
 * NewReceiptFromJSON parses a transaction receipt from a JSON data dump.
 */
FOUNDATION_EXPORT Web3goReceipt* Web3goNewReceiptFromJSON(NSString* data, NSError** error);

/**
 * NewReceiptFromRLP parses a transaction receipt from an RLP data dump.
 */
FOUNDATION_EXPORT Web3goReceipt* Web3goNewReceiptFromRLP(NSData* data, NSError** error);

/**
 * NewTopics creates a slice of uninitialized Topics.
 */
FOUNDATION_EXPORT Web3goTopics* Web3goNewTopics(long size);

/**
 * NewTopicsEmpty creates an empty slice of Topics values.
 */
FOUNDATION_EXPORT Web3goTopics* Web3goNewTopicsEmpty(void);

/**
 * NewTransaction creates a new transaction with the given properties.
 */
FOUNDATION_EXPORT Web3goTransaction* Web3goNewTransaction(int64_t nonce, Web3goAddress* to, Web3goBigInt* amount, int64_t gasLimit, Web3goBigInt* gasPrice, NSData* data);

/**
 * NewTransactionFromJSON parses a transaction from a JSON data dump.
 */
FOUNDATION_EXPORT Web3goTransaction* Web3goNewTransactionFromJSON(NSString* data, NSError** error);

/**
 * NewTransactionFromRLP parses a transaction from an RLP data dump.
 */
FOUNDATION_EXPORT Web3goTransaction* Web3goNewTransactionFromRLP(NSData* data, NSError** error);

/**
 * PubkeyToAddress ...
 */
FOUNDATION_EXPORT Web3goAddress* Web3goPubkeyToAddress(Web3goPublicKey* pub);

/**
 * RinkebyGenesis returns the JSON spec to use for the Rinkeby test network
 */
FOUNDATION_EXPORT NSString* Web3goRinkebyGenesis(void);

/**
 * SaveECDSA ...
 */
FOUNDATION_EXPORT BOOL Web3goSaveECDSA(NSString* file, Web3goPrivateKey* wpriv, NSError** error);

/**
 * Sender ...
 */
FOUNDATION_EXPORT Web3goAddress* Web3goSender(Web3goSigner2* ws, Web3goTransaction* wtx, NSError** error);

/**
 * SetVerbosity sets the global verbosity level (between 0 and 6 - see logger/verbosity.go).
 */
FOUNDATION_EXPORT void Web3goSetVerbosity(long level);

/**
 * SigToPub ...
 */
FOUNDATION_EXPORT Web3goPublicKey* Web3goSigToPub(NSData* hash, NSData* sig, NSError** error);

/**
 * Sign ...
 */
FOUNDATION_EXPORT NSData* Web3goSign(NSData* hash, Web3goPrivateKey* wprv, NSError** error);

/**
 * SignTx ...
 */
FOUNDATION_EXPORT Web3goTransaction* Web3goSignTx(Web3goTransaction* wtx, Web3goSigner2* ws, Web3goPrivateKey* wprv, NSError** error);

/**
 * TestnetGenesis returns the JSON spec to use for the Ethereum test network.
 */
FOUNDATION_EXPORT NSString* Web3goTestnetGenesis(void);

/**
 * ToECDSA ...
 */
FOUNDATION_EXPORT Web3goPrivateKey* Web3goToECDSA(NSData* d, NSError** error);

/**
 * ToECDSAUnsafe ...
 */
FOUNDATION_EXPORT Web3goPrivateKey* Web3goToECDSAUnsafe(NSData* d);

/**
 * UnmarshalPubkey ...
 */
FOUNDATION_EXPORT Web3goPublicKey* Web3goUnmarshalPubkey(NSData* pub, NSError** error);

/**
 * VerifySignature ...
 */
FOUNDATION_EXPORT BOOL Web3goVerifySignature(NSData* pubkey, NSData* hash, NSData* sig);

@class Web3goFilterLogsHandler;

@class Web3goNewHeadHandler;

@class Web3goSigner;

/**
 * FilterLogsHandler is a client-side subscription callback to invoke on events and
subscription failure.
 */
@interface Web3goFilterLogsHandler : NSObject <goSeqRefInterface, Web3goFilterLogsHandler> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onError:(NSString*)failure;
- (void)onFilterLogs:(Web3goLog*)log;
@end

/**
 * NewHeadHandler is a client-side subscription callback to invoke on events and
subscription failure.
 */
@interface Web3goNewHeadHandler : NSObject <goSeqRefInterface, Web3goNewHeadHandler> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onError:(NSString*)failure;
- (void)onNewHead:(Web3goHeader*)header;
@end

/**
 * Signer is an interaface defining the callback when a contract requires a
method to sign the transaction before submission.
 */
@interface Web3goSigner : NSObject <goSeqRefInterface, Web3goSigner> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (Web3goTransaction*)sign:(Web3goAddress*)p0 p1:(Web3goTransaction*)p1 error:(NSError**)error;
@end

#endif
